mapper_global = {
"Afghanistan": "AFG",
"Albania": "ALB",
"Algeria": "DZA",
"Andorra": "AND",
"Angola": "AGO",
"Antigua and Barbuda": "ATG",
"Azerbaijan": "AZE",
"Argentina": "ARG",
"Australia": "AUS",
"Austria": "AUT",
"Bahamas": "BHS",
"Bahrain": "BHR",
"Bangladesh": "BGD",
"Armenia": "ARM",
"Barbados": "BRB",
"Belgium": "BEL",
"Bhutan": "BTN",
"Bolivia": "BOL",
"Bosnia and Herzegovina": "BIH",
"Brazil": "BRA",
"Belize": "BLZ",
"Brunei": "BRN",
"Bulgaria": "BGR",
"Belarus": "BLR",
"Cambodia": "KHM",
"Cameroon": "CMR",
"Canada": "CAN",
"Cabo Verde": "CPV",
"Central African Republic": "CAF",
"Sri Lanka": "LKA",
"Chad": "TCD",
"Chile": "CHL",
"China": "CHN",
"Taiwan*": "TWN",
"Colombia": "COL",
"Congo (Brazzaville)": "COG",
"Congo (Kinshasa)": "COD",
"Costa Rica": "CRI",
"Croatia": "HRV",
"Cuba": "CUB",
"Cyprus": "CYP",
"Czechia": "CZE",
"Benin": "BEN",
"Denmark": "DNK",
"Dominica": "DMA",
"Dominican Republic": "DOM",
"Ecuador": "ECU",
"El Salvador": "SLV",
"Equatorial Guinea": "GNQ",
"Ethiopia": "ETH",
"Eritrea": "ERI",
"Estonia": "EST",
"Fiji": "FJI",
"Finland": "FIN",
"France": "FRA",
"Djibouti": "DJI",
"Gabon": "GAB",
"Georgia": "GEO",
"Gambia": "GMB",
"Germany": "DEU",
"Ghana": "GHA",
"Greece": "GRC",
"Grenada": "GRD",
"Guatemala": "GTM",
"Guinea": "GIN",
"Guyana": "GUY",
"Haiti": "HTI",
"Holy See": "VAT",
"Honduras": "HND",
"Hungary": "HUN",
"Iceland": "ISL",
"India": "IND",
"Indonesia": "IDN",
"Iran": "IRN",
"Iraq": "IRQ",
"Ireland": "IRL",
"Israel": "ISR",
"Italy": "ITA",
"Cote d'Ivoire": "CIV",
"Jamaica": "JAM",
"Japan": "JPN",
"Kazakhstan": "KAZ",
"Jordan": "JOR",
"Kenya": "KEN",
"Korea, South": "KOR",
"Kuwait": "KWT",
"Kyrgyzstan": "KGZ",
"Laos": "LAO",
"Lebanon": "LBN",
"Latvia": "LVA",
"Liberia": "LBR",
"Libya": "LBY",
"Liechtenstein": "LIE",
"Lithuania": "LTU",
"Luxembourg": "LUX",
"Madagascar": "MDG",
"Malaysia": "MYS",
"Maldives": "MDV",
"Malta": "MLT",
"Mauritania": "MRT",
"Mauritius": "MUS",
"Mexico": "MEX",
"Monaco": "MCO",
"Mongolia": "MNG",
"Moldova": "MDA",
"Montenegro": "MNE",
"Morocco": "MAR",
"Mozambique": "MOZ",
"Oman": "OMN",
"Namibia": "NAM",
"Nepal": "NPL",
"Netherlands": "NLD",
"New Zealand": "NZL",
"Nicaragua": "NIC",
"Niger": "NER",
"Nigeria": "NGA",
"Norway": "NOR",
"Pakistan": "PAK",
"Panama": "PAN",
"Papua New Guinea": "PNG",
"Paraguay": "PRY",
"Peru": "PER",
"Philippines": "PHL",
"Poland": "POL",
"Portugal": "PRT",
"Timor-Leste": "TLS",
"Qatar": "QAT",
"Romania": "ROU",
"Russia": "RUS",
"Rwanda": "RWA",
"Saint Lucia": "LCA",
"Saint Vincent and the Grenadines": "VCT",
"San Marino": "SMR",
"Saudi Arabia": "SAU",
"Senegal": "SEN",
"Serbia": "SRB",
"Seychelles": "SYC",
"Singapore": "SGP",
"Slovakia": "SVK",
"Vietnam": "VNM",
"Slovenia": "SVN",
"Somalia": "SOM",
"South Africa": "ZAF",
"Zimbabwe": "ZWE",
"Spain": "ESP",
"Sudan": "SDN",
"Suriname": "SUR",
"Eswatini": "SWZ",
"Sweden": "SWE",
"Switzerland": "CHE",
"Syria": "SYR",
"Thailand": "THA",
"Togo": "TGO",
"Trinidad and Tobago": "TTO",
"United Arab Emirates": "ARE",
"Tunisia": "TUN",
"Turkey": "TUR",
"Uganda": "UGA",
"Ukraine": "UKR",
"North Macedonia": "MKD",
"Egypt": "EGY",
"United Kingdom": "GBR",
"Tanzania": "TZA",
"US": "USA",
"Burkina Faso": "BFA",
"Uruguay": "URY",
"Uzbekistan": "UZB",
"Venezuela": "VEN",
"Zambia": "ZMB",
}


mapper_ru = {
"Altayskiy kray": "RU-ALT",
"Amursk oblast": "RU-AMU",
"Arkhangelsk oblast": "RU-ARK",
"Astrahan oblast": "RU-AST",
"Belgorod oblast": "RU-BEL",
"Briansk oblast": "RU-BRY",
"Vladimir oblast": "RU-VLA",
"Volgograd oblast": "RU-VGG",
"Vologda oblast": "RU-VLG",
"Voronezh oblast": "RU-VOR",
"Moscow": "RU-MOW",
"Saint Petersburg": "RU-SPE",
"Sevastopol": "UA-40",
"Jewish Autonomous oblast": "RU-YEV",
"Zabaykalskiy kray": "RU-ZAB",
"Ivanovo oblast": "RU-IVA",
"Irkutsk oblast": "RU-IRK",
"Kaliningrad oblast": "RU-KGD",
"Kaluga oblast": "RU-KLU",
"Kamchatskiy kray": "RU-KAM",
"Kemerovo oblast": "RU-KEM",
"Kirov oblast": "RU-KIR",
"Kostroma oblast": "RU-KOS",
"Krasnodarskiy kray": "RU-KDA",
"Krasnoyarskiy kray": "RU-KYA",
"Kurgan oblast": "RU-KGN",
"Kursk oblast": "RU-KRS",
"Leningradskaya oblast": "RU-LEN",
"Lipetsk oblast": "RU-LIP",
"Magadan oblast": "RU-MAG",
"Moscow oblast": "RU-MOS",
"Murmansk oblast": "RU-MUR",
"Nenetskiy autonomous oblast": "RU-NEN",
"Nizhegorodskaya oblast": "RU-NIZ",
"Novgorod oblast": "RU-NGR",
"Novosibirsk oblast": "RU-NVS",
"Omsk oblast": "RU-OMS",
"Orenburg oblast": "RU-ORE",
"Orel oblast": "RU-ORL",
"Pensa oblast": "RU-PNZ",
"Perm oblast": "RU-PER",
"Primorskiy kray": "RU-PRI",
"Pskov oblast": "RU-PSK",
"Republic of Adygeia": "RU-AD",
"Altay republic": "RU-AL",
"Republic of Bashkortostan": "RU-BA",
"Republic of Buriatia": "RU-BU",
"Republic of Dagestan": "RU-DA",
"Ingushetia republic": "RU-IN",
"Republic of Kabardino-Balkaria": "RU-KB",
"Republic of Kalmykia": "RU-KL",
"Republic of Karachaevo-Cherkessia": "RU-KC",
"Republic of Karelia": "RU-KR",
"Komi republic": "RU-KO",
"Republic of Crimea": "UA-43",
"Republic of Mariy El": "RU-ME",
"Republic of Mordovia": "RU-MO",
"Saha republic": "RU-SA",
"Republic of North Osetia - Alania": "RU-SE",
"Republic of Tatarstan": "RU-TA",
"Republic of Tyva": "RU-TY",
"Republic of Udmurtia": "RU-UD",
"Republic of Hakassia": "RU-KK",
"Chechen republic": "RU-CE",
"Rostov oblast": "RU-ROS",
"Ryazan oblast": "RU-RYA",
"Samara oblast": "RU-SAM",
"Saratov oblast": "RU-SAR",
"Sakhalin oblast": "RU-SAK",
"Sverdlov oblast": "RU-SVE",
"Smolensk oblast": "RU-SMO",
"Stavropolskiy kray": "RU-STA",
"Tambov oblast": "RU-TAM",
"Tver oblast": "RU-TVE",
"Tomsk oblast": "RU-TOM",
"Tula oblast": "RU-TUL",
"Tumen oblast": "RU-TYU",
"Ulianovsk oblast": "RU-ULY",
"Habarovskiy kray": "RU-KHA",
"Hanty-Mansiyskiy AO": "RU-KHM",
"Cheliabinsk oblast": "RU-CHE",
"Republic of Chuvashia": "RU-CU",
"Chukotskiy autonomous oblast": "RU-CHU",
"Yamalo-Nenetskiy AO": "RU-YAN",
"Yaroslavl oblast": "RU-YAR",
}